// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etysnilrceunntujuvby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0eXNuaWxyY2V1bm50dWp1dmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDcxNTgsImV4cCI6MjA2NTA4MzE1OH0.OvS1MH0YcYBHrLzSkQFpW27Y5FzQxQo6ccv7uChVUt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);